services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: turnero
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    command: 
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_general_ci 
      - --default-time-zone=+00:00
      - --innodb-buffer-pool-size=128M
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - turnero-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      timeout: 30s
      retries: 15
      start_period: 60s
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "rootpassword"
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - turnero-network

volumes:
  db_data:

networks:
  turnero-network:
    driver: bridge  # Cambia de external a bridge