version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: turnero
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./turnero.sql:/docker-entrypoint-initdb.d/turnero.sql
    networks:
      - turnero-network

volumes:
  db_data:

networks:
  turnero-network:
    external: true