services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: turnero
    command: 
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_general_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./turnero.sql:/docker-entrypoint-initdb.d/turnero.sql 
    networks:
      - turnero-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      timeout: 30s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "rootpassword"
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - turnero-network

volumes:
  db_data:

networks:
  turnero-network:
    external: false 